excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Pokemap/AppDelegate.swift

disabled_rules:
  - todo
function_body_length:
  warning: 200
  error: 300
line_length:
  warning: 120
  error: 150
variable_name:
  excluded: # excluded via string array
    - LOGIN_URL
    - LOGIN_OAUTH
    - PTC_CLIENT_SECRET
    - API_SKIPLAGGED
    - API_GENERAL
    - API_SPECIFIC
    - PROFILE_RAW
    - PROFILE
